import os
from datetime import datetime
from functools import wraps
from flask import Flask, render_template, request, redirect, url_for, session, flash
from sqlalchemy import create_engine, text, inspect

app = Flask(__name__)
app.secret_key = os.environ.get('SECRET_KEY', 'change-this-secret')
ADMIN_PASSWORD = os.environ.get('ADMIN_PASSWORD', 'change-me')

DATABASE_URL = os.environ.get('DATABASE_URL', '').strip()
if DATABASE_URL.startswith('postgres://'):
    DATABASE_URL = DATABASE_URL.replace('postgres://', 'postgresql://', 1)
if not DATABASE_URL:
    DATABASE_URL = 'sqlite:///leads.db'

engine = create_engine(DATABASE_URL, pool_pre_ping=True)

def init_db():
    with engine.begin() as conn:
        conn.execute(text('''
            CREATE TABLE IF NOT EXISTS leads (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                created_at TEXT,
                name TEXT,
                phone TEXT,
                email TEXT,
                service TEXT,
                notes TEXT,
                appointment_date TEXT,
                appointment_time TEXT,
                status TEXT DEFAULT 'New',
                source TEXT DEFAULT 'Direct / Unknown'
            )
        ''' if engine.dialect.name == 'postgresql' else '''
            CREATE TABLE IF NOT EXISTS leads (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                created_at TEXT,
                name TEXT,
                phone TEXT,
                email TEXT,
                service TEXT,
                notes TEXT,
                appointment_date TEXT,
                appointment_time TEXT,
                status TEXT DEFAULT 'New',
                source TEXT DEFAULT 'Direct / Unknown'
            )
        '''))

    cols = {c['name'] for c in inspect(engine).get_columns('leads')}
    if 'source' not in cols:
        with engine.begin() as conn:
            conn.execute(text("ALTER TABLE leads ADD COLUMN source TEXT DEFAULT 'Direct / Unknown'"))

init_db()

def admin_required(f):
    @wraps(f)
    def w(*a, **k):
        return f(*a, **k) if session.get('admin') else redirect(url_for('admin_login'))
    return w

@app.route('/', methods=['GET', 'POST'])
def home():
    if request.method == 'POST':
        name = request.form.get('name', '').strip()
        phone = request.form.get('phone', '').strip()
        if not name or not phone:
            flash('Name and phone are required.')
            return redirect('/')

        source = request.form.get('source', '').strip() or 'Direct / Unknown'
        with engine.begin() as conn:
            conn.execute(text('''
                INSERT INTO leads
                (created_at, name, phone, email, service, notes, appointment_date, appointment_time, source)
                VALUES
                (:created_at, :name, :phone, :email, :service, :notes, :appointment_date, :appointment_time, :source)
            '''), {
                'created_at': datetime.now().isoformat(timespec='seconds'),
                'name': name,
                'phone': phone,
                'email': request.form.get('email', ''),
                'service': request.form.get('service', ''),
                'notes': request.form.get('notes', ''),
                'appointment_date': request.form.get('appointment_date', ''),
                'appointment_time': request.form.get('appointment_time', ''),
                'source': source,
            })
        return redirect('/thank-you')

    source = request.args.get('source', '').strip() or 'Direct / Unknown'
    return render_template('index.html', source=source)

@app.route('/thank-you')
def thanks():
    return render_template('thank_you.html')

@app.route('/admin/login', methods=['GET', 'POST'])
def admin_login():
    if request.method == 'POST' and request.form.get('password') == ADMIN_PASSWORD:
        session['admin'] = True
        return redirect('/admin')
    return render_template('admin_login.html')

@app.route('/admin')
@admin_required
def admin():
    with engine.connect() as conn:
        leads = conn.execute(text('SELECT * FROM leads ORDER BY id DESC')).mappings().all()
    return render_template('admin.html', leads=leads)

@app.route('/admin/logout')
def logout():
    session.clear()
    return redirect('/admin/login')

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=int(os.environ.get('PORT', 5000)))
