import os
import json
import urllib.request
import urllib.error
from datetime import datetime
from functools import wraps
from flask import Flask, render_template, request, redirect, url_for, session, flash
from sqlalchemy import create_engine, text, inspect

app = Flask(__name__)
app.secret_key = os.environ.get('SECRET_KEY', 'change-this-secret')
ADMIN_PASSWORD = os.environ.get('ADMIN_PASSWORD', 'change-me')

DATABASE_URL = os.environ.get('DATABASE_URL', '').strip()
if DATABASE_URL.startswith('postgres://'):
    DATABASE_URL = DATABASE_URL.replace('postgres://', 'postgresql://', 1)
if not DATABASE_URL:
    DATABASE_URL = 'sqlite:///leads.db'

engine = create_engine(DATABASE_URL, pool_pre_ping=True)

RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '').strip()
RESEND_FROM = os.environ.get('RESEND_FROM', 'Happys Appointments <onboarding@resend.dev>').strip()
RESEND_RECIPIENTS = [x.strip() for x in os.environ.get('RESEND_RECIPIENTS', 'davinsmith03@gmail.com,sam@happysappliances.com').split(',') if x.strip()]

def init_db():
    with engine.begin() as conn:
        conn.execute(text('''
            CREATE TABLE IF NOT EXISTS leads (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                created_at TEXT,
                name TEXT,
                phone TEXT,
                email TEXT,
                service TEXT,
                notes TEXT,
                appointment_date TEXT,
                appointment_time TEXT,
                status TEXT DEFAULT 'New',
                source TEXT DEFAULT 'Direct / Unknown'
            )
        ''' if engine.dialect.name == 'postgresql' else '''
            CREATE TABLE IF NOT EXISTS leads (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                created_at TEXT,
                name TEXT,
                phone TEXT,
                email TEXT,
                service TEXT,
                notes TEXT,
                appointment_date TEXT,
                appointment_time TEXT,
                status TEXT DEFAULT 'New',
                source TEXT DEFAULT 'Direct / Unknown'
            )
        '''))

    cols = {c['name'] for c in inspect(engine).get_columns('leads')}
    if 'source' not in cols:
        with engine.begin() as conn:
            conn.execute(text("ALTER TABLE leads ADD COLUMN source TEXT DEFAULT 'Direct / Unknown'"))

init_db()

def format_appointment(date_value, time_value):
    try:
        date_text = datetime.strptime(date_value, '%Y-%m-%d').strftime('%m/%d/%Y') if date_value else 'Not selected'
    except ValueError:
        date_text = date_value or 'Not selected'
    try:
        time_text = datetime.strptime(time_value, '%H:%M').strftime('%-I:%M %p') if time_value else 'Not selected'
    except (ValueError, OSError):
        try:
            time_text = datetime.strptime(time_value, '%H:%M').strftime('%I:%M %p').lstrip('0') if time_value else 'Not selected'
        except ValueError:
            time_text = time_value or 'Not selected'
    return f'{time_text} {date_text}'

def send_appointment_email(lead):
    if not RESEND_API_KEY:
        msg = 'FAILED: RESEND_API_KEY is not configured in Render.'
        app.logger.warning(msg)
        return msg

    body = f"""New appointment request

Name: {lead['name']}
Phone: {lead['phone']}
Email: {lead['email'] or 'Not provided'}
Location: {lead['service'] or 'Not selected'}
Requested appointment: {format_appointment(lead['appointment_date'], lead['appointment_time'])}
Source: {lead['source']}
Notes: {lead['notes'] or 'None'}
"""

    payload = json.dumps({
        'from': RESEND_FROM,
        'to': RESEND_RECIPIENTS,
        'subject': f"New Happys appointment request - {lead['name']}",
        'text': body,
    }).encode('utf-8')

    req = urllib.request.Request(
        'https://api.resend.com/emails',
        data=payload,
        headers={
            'Authorization': f'Bearer {RESEND_API_KEY}',
            'Content-Type': 'application/json',
            'User-Agent': 'happys-appointment-site/1.0',
        },
        method='POST',
    )

    try:
        with urllib.request.urlopen(req, timeout=20) as response:
            response_body = response.read().decode('utf-8', errors='replace')
            msg = f'SENT: Resend accepted the email ({response.status}). {response_body}'
            app.logger.info(msg)
            return msg
    except urllib.error.HTTPError as exc:
        response_body = exc.read().decode('utf-8', errors='replace')
        msg = f'FAILED: Resend returned HTTP {exc.code}. {response_body}'
        app.logger.error(msg)
        return msg
    except Exception as exc:
        msg = f'FAILED: {type(exc).__name__}: {exc}'
        app.logger.exception(msg)
        return msg

def admin_required(f):
    @wraps(f)
    def w(*a, **k):
        return f(*a, **k) if session.get('admin') else redirect(url_for('admin_login'))
    return w

@app.route('/', methods=['GET', 'POST'])
def home():
    if request.method == 'POST':
        name = request.form.get('name', '').strip()
        phone = request.form.get('phone', '').strip()
        if not name or not phone:
            flash('Name and phone are required.')
            return redirect('/')

        lead = {
            'created_at': datetime.now().isoformat(timespec='seconds'),
            'name': name,
            'phone': phone,
            'email': request.form.get('email', '').strip(),
            'service': request.form.get('service', '').strip(),
            'notes': request.form.get('notes', '').strip(),
            'appointment_date': request.form.get('appointment_date', '').strip(),
            'appointment_time': request.form.get('appointment_time', '').strip(),
            'source': request.form.get('source', '').strip() or 'Direct / Unknown',
        }

        with engine.begin() as conn:
            conn.execute(text('''
                INSERT INTO leads
                (created_at, name, phone, email, service, notes, appointment_date, appointment_time, source)
                VALUES
                (:created_at, :name, :phone, :email, :service, :notes, :appointment_date, :appointment_time, :source)
            '''), lead)

        email_status = send_appointment_email(lead)
        if name.upper().startswith('EMAIL TEST'):
            session['email_debug'] = email_status
        return redirect('/thank-you')

    source = request.args.get('source', '').strip() or 'Direct / Unknown'
    return render_template('index.html', source=source)

@app.route('/thank-you')
def thanks():
    email_debug = session.pop('email_debug', None)
    return render_template('thank_you.html', email_debug=email_debug)

@app.route('/admin/login', methods=['GET', 'POST'])
def admin_login():
    if request.method == 'POST' and request.form.get('password') == ADMIN_PASSWORD:
        session['admin'] = True
        return redirect('/admin')
    return render_template('admin_login.html')

@app.route('/admin')
@admin_required
def admin():
    with engine.connect() as conn:
        leads = conn.execute(text('SELECT * FROM leads ORDER BY id DESC')).mappings().all()
    return render_template('admin.html', leads=leads)

@app.route('/admin/logout')
def logout():
    session.clear()
    return redirect('/admin/login')

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=int(os.environ.get('PORT', 5000)))
